name = "portfolio"
main = "src/index.ts"
compatibility_date = "2025-10-01"

[assets]
directory = "src/"
not_found_handling = "single-page-application"

[env.dev]
workers_dev = true
route = "staging.example.com/*"

[env.production]
workers_dev = false
route = "jncodes.pro/*"
pages_build_output_dir = "dist/client"
account_id = "782fcc0bba1e9f71c8d3d6a90bf6d95c"
zone_id = "ec8cc3a762b32364d2ed8436571bd16a"
